kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx6g
org.gradle.jvmargs=-XX:MaxMetaspaceSize=1024m -Xmx6g -Dfile.encoding=UTF-8

# Also fix buildSrc/gradle.properties!
saxonVersion=12.9
docbookVersion=5.2
xslTNGversion=2.6.1

# This one is used in the processor, not just the documentation
schxslt2=1.4.4

xmlcalabashGroup=com.xmlcalabash
xmlcalabashVersion=3.0.19-SNAPSHOT
// name is defined in settings.gradle.kts

builtBy=Norm Tovey-Walsh
