#+TITLE: XML Calabash 3.x

This is XML Calabash 3.x, a conformant implementation of
[[https://spec.xproc.org/3.1/xproc/][XProc 3.1]].

XML Calabash implements the standard step library
and the additional step libraries:
[[https://spec.xproc.org/3.1/run/][dynamic pipelines (p:run)]],
[[https://spec.xproc.org/3.1/file/][file steps]],
[[https://spec.xproc.org/3.1/os/][OS steps]],
[[https://spec.xproc.org/3.1/mail/][mail steps]],
[[https://spec.xproc.org/3.1/paged-media/][paged media steps]],
[[https://spec.xproc.org/3.1/text/][text steps]],
[[https://spec.xproc.org/3.1/validation/][validation steps]], and
[[https://spec.xproc.org/3.1/ixml/][iXML steps]]. It also ships with
[[https://docs.xmlcalabash.com/reference/current/extension-steps.html][a number]] of extension steps.

Instructions for installing and running the command line application are in the
[[https://docs.xmlcalabash.com/userguide/current/][User Guide]]. The [[https://docs.xmlcalabash.com/reference/current/][Reference Guide]] describes all of the steps and other details.

[[https://docs.xmlcalabash.com/apidocs/current/][API docs]] are available, but at this point, the API should be considered unstable
and liable to change in arbitrary ways.

The [[https://xmlcalabash.com/test-report/current/][test report]] provides some insights into what is expected to work and what is
known to be broken.

* Quick start
:PROPERTIES:
:CUSTOM_ID: quick-start
:END:

XML Calabash requires Java 11 or later. Everything else is in the distribution.

1. Download the [[https://codeberg.org/xmlcalabash/xmlcalabash3/releases][latest release]]. You need ~xmlcalabash-3.X.Y.zip~ where “X” and “Y”
   are the release number (for example, 3.0.0).
   The other zip files on the release page are extension steps with additional
   third party dependencies. You have to download them too, if you want to use
   those steps.
2. Unzip it somewhere on your local file system.
3. Run ~java -jar xmlcalabash-app-3.X.Y.jar help~ to see a quick list of the options.
4. Run ~java -jar xmlcalabash-app-3.X.Y.jar helloWorld.xpl~ to run the sample pipeline.

There are more complete instructions in the [[https://docs.xmlcalabash.com/userguide/current/][User Guide]].

** Running the main class
:PROPERTIES:
:CUSTOM_ID: running
:END:

The main class for the command line application is ~com.xmlcalabash.app.Main~.
You can run that class directly, but you’ll have to setup the classpath by hand.
You can find the necessary jar files in the release archive. Dependencies
[[https://docs.xmlcalabash.com/reference/current/ch01.html][are discussed]] in the [[https://docs.xmlcalabash.com/reference/current/][Reference Guide]].

** Using with Maven
:PROPERTIES:
:CUSTOM_ID: maven
:END:

Maven releases are available [[https://central.sonatype.com/][Maven Central]].

Snapshot releases of current development are available from
[[https://central.sonatype.com/service/rest/repository/browse/maven-snapshots/][the snapshot repository]].

* Reporting issues
:PROPERTIES:
:CUSTOM_ID: issues
:END:

Please [[https://codeberg.org/xmlcalabash/xmlcalabash3/issues][open issues]] for any problems you encounter. There are going to be bugs,
so it’s probably not you.

