package com.xmlcalabash.util.fileselector

import net.sf.saxon.om.NamespaceUri
import net.sf.saxon.s9api.QName

object NsFs {
    val namespace: NamespaceUri = NamespaceUri.NULL

    val allowTie = QName(namespace, "allow-tie")
    val and = QName(namespace, "and")
    val caseSensitive = QName(namespace, "case-sensitive")
    val chainedMapper = QName(namespace, "chained-mapper")
    val compositeMapper = QName(namespace, "composite-mapper")
    val contains = QName(namespace, "contains")
    val containsRegexp = QName(namespace, "contains-regexp")
    val contentType = QName(namespace, "content-type")
    val cutDirsMapper = QName(namespace, "cut-dirs-mapper")
    val date = QName(namespace, "date")
    val dateTime = QName(namespace, "date-time")
    val defaultExcludes = QName(namespace, "default-excludes")
    val depend = QName(namespace, "depend")
    val depth = QName(namespace, "depth")
    val different = QName(namespace, "different")
    val dirs = QName(namespace, "dirs")
    val errorOnMissingDir = QName(namespace, "error-on-missing-dir")
    val exclude = QName(namespace, "exclude")
    val excludes = QName(namespace, "excludes")
    val executable = QName(namespace, "executable")
    val expression = QName(namespace, "expression")
    val filename = QName(namespace, "filename")
    val fileset = QName(namespace, "fileset")
    val firstMatchMapper = QName(namespace, "first-match-mapper")
    val flattenMapper = QName(namespace, "flatten-mapper")
    val followSymlinks = QName(namespace, "follow-symlinks")
    val globMapper = QName(namespace, "glob-mapper")
    val granularity = QName(namespace, "granularity")
    val group = QName(namespace, "group")
    val identityMapper = QName(namespace, "identity-mapper")
    val `if` = QName(namespace, "if")
    val ignoreContents = QName(namespace, "ignore-contents")
    val ignoreFileTimes = QName(namespace, "ignore-file-times")
    val ignoreWhitespace = QName(namespace, "ignore-whitespace")
    val include = QName(namespace, "include")
    val includes = QName(namespace, "includes")
    val majority = QName(namespace, "majority")
    val mapper = QName(namespace, "mapper")
    val max = QName(namespace, "max")
    val mergeMapper = QName(namespace, "merge-mapper")
    val min = QName(namespace, "min")
    val multiLine = QName(namespace, "multi-line")
    val negate = QName(namespace, "negate")
    val none = QName(namespace, "none")
    val not = QName(namespace, "not")
    val regex = QName(namespace, "regex")
    val or = QName(namespace, "or")
    val ownedBy = QName(namespace, "owned-by")
    val owner = QName(namespace, "owner")
    val packageMapper = QName(namespace, "package-mapper")
    val posixGroup = QName(namespace, "posix-group")
    val present = QName(namespace, "present")
    val readable = QName(namespace, "readable")
    val regexpMapper = QName(namespace, "regexp-mapper")
    val singleLine = QName(namespace, "single-line")
    val size = QName(namespace, "size")
    val symlink = QName(namespace, "symlink")
    val targetDir = QName(namespace, "target-dir")
    val text = QName(namespace, "text")
    val type = QName(namespace, "type")
    val units = QName(namespace, "units")
    val unless = QName(namespace, "unless")
    val unpackageMapper = QName(namespace, "unpackage-mapper")
    val value = QName(namespace, "value")
    val `when` = QName(namespace, "when")
    val writable = QName(namespace, "writable")

}