when:
  - event: push
    branch: ci-testing

steps:
  - name: build
    image: xmlcalabash-build
    environment:
      GRAALVM_HOME: /usr/lib/jvm/graalvm-community-openjdk-21.0.2+13.1
      ENV JAVA_HOME: /usr/lib/jvm/graalvm-community-openjdk-21.0.2+13.1
    commands:
      - git submodule init
      - git submodule update
      - ./gradlew --console=plain test
  - name: test-report
    image: xmlcalabash-build
    commands:
      - echo ./gradlew --console=plain test-driver:test-report

