when:
  - event: push
    branch: ci-testing

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

steps:
  - name: build
    image: xmlcalabash-build
    environment:
      LIBRARY_PASSPHRASE:
        from_secret: LIBRARY_PASSPHRASE
      SMTPSERVER: sendria
    commands:
      - cat /private/xmlcalabash-libs.enc | openssl enc -aes-256-cbc -salt -pbkdf2 -d -k $${LIBRARY_PASSPHRASE} | tar zxf -
      - ./gradlew --console=plain test 
  - name: test-report
    image: xmlcalabash-build
    commands:
      - ./gradlew --console=plain -PWHOST=http://apache2 -PSHOST=sendria test-driver:quick-report

services:
  - name: apache2
    image: apache2
    volumes:
      - xproc-test-suite-apache2:/usr/local/apache2

  - name: sendria
    image: sendria
    environment:
      MAIL_DRIVER: smtp
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 1025
      MAIL_USERNAME: username
      MAIL_PASSWORD: password
      MAIL_ENCRYPTION: tcp
      MAIL_FROM_ADDRESS: nobody@example.com
