when:
  - event: [push, tag]
    branch: main

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

steps:
  - name: build-and-test
    image: xmlcalabash-build
    volumes:
      - builder-home:/home/builder
    environment:
      LIBRARY_PASSPHRASE:
        from_secret: LIBRARY_PASSPHRASE
      SMTPSERVER: sendria
      GRADLE_USER_HOME: ./build/.gradle
    commands:
      # This build has to run as a non-root user
      - sudo chown -R builder:builder .
      # Avoid Invalid Java installation found at '/home/builder/.gradle/.tmp/jdks/... ???
      - rm -rf /home/builder/.gradle/.tmp
      - cat /private/xmlcalabash-libs.enc | openssl enc -aes-256-cbc -salt -pbkdf2 -d -k $${LIBRARY_PASSPHRASE} | tar zxf -
      - ./gradlew --console=plain --max-workers=2 test 

  - name: setup-gradle
    volumes:
      - builder-home:/home/builder
    commands:
      - cp /home/builder/.gradle/gradle.properties ./build/.gradle/

  - name: test-suites
    image: xmlcalabash-build
    volumes:
      - builder-home:/home/builder
    environment:
      GRADLE_USER_HOME: ./build/.gradle
    commands:
      - ./gradlew --console=plain --max-workers=2 -PWHOST=http://apache2 -PSHOST=sendria test-driver:test-report

  - name: documentation
    image: xmlcalabash-build
    volumes:
      - builder-home:/home/builder
    environment:
      GRADLE_USER_HOME: ./build/.gradle
    commands:
      - ./gradlew --console=plain documentation:reference documentation:userguide
      - ./gradlew --console=plain documentation:publishTestSuites
      - ./gradlew --console=plain xmlcalabash:apidocs dokkaHtmlMultiModule
      - ./gradlew --console=plain apidocs release

  - name: checkout www.xmlcalabash.com
    image: xmlcalabash-build
    volumes:
      - builder-home:/home/builder
    commands:
      - cd build
      - git clone ssh://git@codeberg.org/xmlcalabash/www.git

  - name: update the current test-suites
    image: xmlcalabash-build
    volumes:
      - builder-home:/home/builder
    commands:
      - cd build/www
      - export VERSION=`cat gradle.properties|grep xmlcalabashVersion|cut -f2 -d=`
      - export SNAPSHOT=`echo $VERSION | grep SNAPSHOT`
      - rsync -ar --delete /woodpecker/src/codeberg.org/xmlcalabash/xmlcalabash3/documentation/build/test-suites/ src/main/test-suites/

  - name: update the tagged test-report
    when: 
      - evaluate: '$CI_COMMIT_TAG != "" && not ($CI_COMMIT_TAG contains "SNAPSHOT")'
    image: xmlcalabash-build
    volumes:
      - builder-home:/home/builder
    commands:
      - cd build/www
      - mkdir -p src/main/test-report/$CI_COMMIT_TAG
      - rsync -ar --delete src/main/test-report/current/ src/main/test-report/$CI_COMMIT_TAG/

  - name: update www.xmlcalabash.com
    image: xmlcalabash-build
    volumes:
      - builder-home:/home/builder
    commands:
      - cd build/www
      - git config --global user.email "norm@tovey-walsh.com"
      - git config --global user.name "Norm Tovey-Walsh"
      - git status
      - git add .
      - git commit -m "Updated documentation from XML Calabash build"
      - git push

  - name: checkout docs.xmlcalabash.com
    image: xmlcalabash-build
    volumes:
      - builder-home:/home/builder
    commands:
      - cd build
      - git clone ssh://git@codeberg.org/xmlcalabash/docs.git

  - name: update the documentation
    when: 
      - event: tag
    image: xmlcalabash-build
    volumes:
      - builder-home:/home/builder
    commands:
      - export VERSION=`cat gradle.properties|grep xmlcalabashVersion|cut -f2 -d=`
      - export SNAPSHOT=`echo $VERSION | grep SNAPSHOT`
      - cd build/docs
      - mkdir -p apidocs/$VERSION apidocs/current
      - mkdir -p reference/$VERSION reference/current
      - mkdir -p userguide/$VERSION userguide/current
      - rsync -ar ../../documentation/build/reference/current/ reference/$VERSION/
      - rsync -ar ../../documentation/build/userguide/current/ userguide/$VERSION/
      - rsync -ar ../dokka/htmlMultiModule/ apidocs/$VERSION/
      - rsync -ar reference/$VERSION/ reference/current/
      - rsync -ar userguide/$VERSION/ userguide/current/
      - rsync -ar apidocs/$VERSION/ apidocs/current/
      - rsync -var --checksum reference/$VERSION datamagician:/Volumes/Websites/xcdocs/reference
      - rsync -var --checksum --delete reference/current datamagician:/Volumes/Websites/xcdocs/reference
      - rsync -var --checksum userguide/$VERSION datamagician:/Volumes/Websites/xcdocs/userguide
      - rsync -var --checksum --delete userguide/current datamagician:/Volumes/Websites/xcdocs/userguide
      - rsync -var --checksum apidocs/$VERSION datamagician:/Volumes/Websites/xcdocs/apidocs
      - rsync -var --checksum --delete apidocs/current datamagician:/Volumes/Websites/xcdocs/apidocs

  - name: publish
    image: xmlcalabash-build
    volumes:
      - builder-home:/home/builder
    environment:
      GRADLE_USER_HOME: ./build/.gradle
    commands:
      - export VERSION=`cat gradle.properties|grep xmlcalabashVersion|cut -f2 -d=`
      - export SNAPSHOT=`echo $VERSION | grep SNAPSHOT`
      - echo "TAG $CI_COMMIT_TAG and SNAP $SNAPSHOT"
      - if [ "$CI_COMMIT_TAG" != "" -o "$SNAPSHOT" != "" ]; then
      -   ./gradlew --console=plain publish
      - else
      -   echo "Not publishing $VERSION"
      - fi

  - name: publish-release
    image: woodpeckerci/plugin-release
    when: 
      - event: tag
    settings:
      files:
        - 'app/build/distributions/*.zip'
        - 'ext/polyglot/build/distributions/*.zip'
      api_key:
        from_secret: ACCESS_TOKEN

# N.B. The xproc-test-suite-apache2 container has a complete copy of 
# the /usr/local/apache2 directory (including binaries) from the apache2
# container. Parts of it are (will be!) updated by a different workflow.
services:
  - name: apache2
    image: apache2
    volumes:
      - xproc-test-suite-apache2:/usr/local/apache2

  - name: sendria
    image: sendria
    environment:
      MAIL_DRIVER: smtp
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 1025
      MAIL_USERNAME: username
      MAIL_PASSWORD: password
      MAIL_ENCRYPTION: tcp
      MAIL_FROM_ADDRESS: nobody@example.com
